export const URUN_EKLEME='URUN_EKLEME';
export const URUN_SILME='URUN_SILME';
export const URUN_FIYAT='URUN_FIYAT';
export const SATIN_IPTAL='SATIN_IPTAL';
export const SET_URUNLER='SET_URUNLER';
export const FETCHED_URUNLER_FAILED='FETCHED_URUNLER_FAILED';

export const PURCHASE_ORDER_START='PURCHASE_ORDER_START';
export const PURCHASE_ORDER_SUCCESS='PURCHASE_ORDER_SUCCESS';
export const PURCHASE_ORDER_FAILED='PURCHASE_ORDER_FAILED';
export const PURCHASE_ORDER_INIT='PURCHASE_ORDER_INIT';


export const FETCH_ORDERS_SUCCESS='FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILED='FETCH_ORDERS_FAILED';
export const FETCH_ORDERS_START='FETCH_ORDERS_START';


export const AUTH_SUCCESS='AUTH_SUCCESS';
export const AUTH_FAILED='AUTH_FAILED';
export const AUTH_START='AUTH_START';
export const AUTH_LOGOUT='AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH='SET_AUTH_REDIRECT_PATH';